title: Battleships - An Epistemic Logic Representation #Site title
description: "An epistemic representation of the Battleships game" #Site common description
url: "https://kaeru4343.github.io/LAMAS_2020Project/" # the base hostname & protocol for your site
home-repo: "https://github.com/kaeru4343/LAMAS_2020Project" #Site repository
theme: jekyll-theme-cayman